server {
    listen 80;
    server_name localhost;

    root /var/www/html/public;
    index index.php index.html;

    charset utf-8;

    # Front controller pattern
    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    # Hide dotfiles
    location ~ /\.(?!well-known).* {
        deny all;
    }

    # Pass PHP scripts to php-fpm container
    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        include fastcgi_params;

        # Mitigate httpoxy vulnerability
        fastcgi_param HTTP_PROXY "";

        fastcgi_buffer_size 128k;
        fastcgi_buffers 4 256k;
        fastcgi_busy_buffers_size 256k;
    }
}
